apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: production
  PORT: "3000"
  DATABASE_URL: postgres://postgres:${DB_PASSWORD}@postgres-service:5432/code_editor
  REDIS_URL: redis://:${REDIS_PASSWORD}@redis-service:6379
  FRONTEND_URL: https://your-domain.com
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET_BASE64}
  GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID_BASE64}
  GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET_BASE64}
